### ISSUE TITLE
uform model seems to have failed to download, please check the network, add a proxy, or try again.

### ISSUE THREAD

**Issue by XiaoNieGPT** [yuka-friends/Windrecorder#171]
![image](https://github.com/yuka-friends/Windrecorder/assets/22927944/51b402b1-9ddd-4aba-92ac-51988d458a2c)

**Comment by Antonoko** [comment]
挠头了，可以先试试这里 test.py 的执行输出结果以便于进一步诊断：

https://github.com/yuka-friends/Windrecorder/issues/164#issuecomment-2106111431

**Comment by Lutra-Fs** [comment]
我也遇到了同样的问题，附上log作为参考
```

  This script will install the image semantic indexing function for Windrecorder.
  After installation, you can index and search for corresponding images using natural language descriptions.
  本向导将为捕风记录仪安装图像语义索引功能。安装完毕后，可以索引并用自然语言描述来搜索对应画面。

  ================================================================================

  Installation options (install the download in the virtual environment of Windrecorder, occupying about 4G space):
  安装选项（将下载安装在 Windrecorder 的虚拟环境中，约占用 4G 空间）：

  1. Install a version that supports CUDA acceleration for Nvidia graphics cards;
     安装支持 Nvidia 显卡 CUDA 加速的版本；

  2. Install CPU version; 安装 CPU 版本；


Please enter the options and press Enter:1
Installing an environment that supports CUDA acceleration; 正在安装支持 CUDA 加速的环境
Python 3.11 installed
Running Python 3.11 specific commands...
Warning: Found deprecated priority 'default' for source 'tsinghua' in pyproject.toml. You can achieve the same effect by changing the priority to 'primary' and putting the source first.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: uform in f:\windrecorder\.venv\lib\site-packages (3.0.2)
Requirement already satisfied: huggingface-hub>=0.16.4 in f:\windrecorder\.venv\lib\site-packages (from uform) (0.23.2)
Requirement already satisfied: tokenizers>=0.13.3 in f:\windrecorder\.venv\lib\site-packages (from uform) (0.19.1)
Requirement already satisfied: pillow in f:\windrecorder\.venv\lib\site-packages (from uform) (10.2.0)
Requirement already satisfied: simsimd in f:\windrecorder\.venv\lib\site-packages (from uform) (4.3.1)
Requirement already satisfied: filelock in f:\windrecorder\.venv\lib\site-packages (from huggingface-hub>=0.16.4->uform) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in f:\windrecorder\.venv\lib\site-packages (from huggingface-hub>=0.16.4->uform) (2024.5.0)
Requirement already satisfied: packaging>=20.9 in f:\windrecorder\.venv\lib\site-packages (from huggingface-hub>=0.16.4->uform) (23.2)
Requirement already satisfied: pyyaml>=5.1 in f:\windrecorder\.venv\lib\site-packages (from huggingface-hub>=0.16.4->uform) (6.0.1)
Requirement already satisfied: requests in f:\windrecorder\.venv\lib\site-packages (from huggingface-hub>=0.16.4->uform) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in f:\windrecorder\.venv\lib\site-packages (from huggingface-hub>=0.16.4->uform) (4.66.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in f:\windrecorder\.venv\lib\site-packages (from huggingface-hub>=0.16.4->uform) (4.10.0)
Requirement already satisfied: colorama in f:\windrecorder\.venv\lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.16.4->uform) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in f:\windrecorder\.venv\lib\site-packages (from requests->huggingface-hub>=0.16.4->uform) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in f:\windrecorder\.venv\lib\site-packages (from requests->huggingface-hub>=0.16.4->uform) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in f:\windrecorder\.venv\lib\site-packages (from requests->huggingface-hub>=0.16.4->uform) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in f:\windrecorder\.venv\lib\site-packages (from requests->huggingface-hub>=0.16.4->uform) (2024.2.2)

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
Warning: Found deprecated priority 'default' for source 'tsinghua' in pyproject.toml. You can achieve the same effect by changing the priority to 'primary' and putting the source first.
Collecting torch==2.2.0+cu121
  Using cached https://mirror.sjtu.edu.cn/pytorch-wheels/cu121/torch-2.2.0+cu121-cp311-cp311-win_amd64.whl (2454.8 MB)
Requirement already satisfied: filelock in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121) (4.10.0)
Requirement already satisfied: sympy in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121) (1.12)
Requirement already satisfied: networkx in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121) (3.2.1)
Requirement already satisfied: jinja2 in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121) (3.1.3)
Requirement already satisfied: fsspec in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121) (2024.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in f:\windrecorder\.venv\lib\site-packages (from jinja2->torch==2.2.0+cu121) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in f:\windrecorder\.venv\lib\site-packages (from sympy->torch==2.2.0+cu121) (1.3.0)

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
Warning: Found deprecated priority 'default' for source 'tsinghua' in pyproject.toml. You can achieve the same effect by changing the priority to 'primary' and putting the source first.
Collecting torchaudio==2.2.0+cu121
  Using cached https://mirror.sjtu.edu.cn/pytorch-wheels/cu121/torchaudio-2.2.0+cu121-cp311-cp311-win_amd64.whl (4.1 MB)
Requirement already satisfied: torch==2.2.0+cu121 in f:\windrecorder\.venv\lib\site-packages (from torchaudio==2.2.0+cu121) (2.2.0+cu121)
Requirement already satisfied: filelock in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121->torchaudio==2.2.0+cu121) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121->torchaudio==2.2.0+cu121) (4.10.0)
Requirement already satisfied: sympy in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121->torchaudio==2.2.0+cu121) (1.12)
Requirement already satisfied: networkx in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121->torchaudio==2.2.0+cu121) (3.2.1)
Requirement already satisfied: jinja2 in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121->torchaudio==2.2.0+cu121) (3.1.3)
Requirement already satisfied: fsspec in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121->torchaudio==2.2.0+cu121) (2024.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in f:\windrecorder\.venv\lib\site-packages (from jinja2->torch==2.2.0+cu121->torchaudio==2.2.0+cu121) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in f:\windrecorder\.venv\lib\site-packages (from sympy->torch==2.2.0+cu121->torchaudio==2.2.0+cu121) (1.3.0)

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
Warning: Found deprecated priority 'default' for source 'tsinghua' in pyproject.toml. You can achieve the same effect by changing the priority to 'primary' and putting the source first.
Collecting torchvision==0.17.0+cu121
  Using cached https://mirror.sjtu.edu.cn/pytorch-wheels/cu121/torchvision-0.17.0+cu121-cp311-cp311-win_amd64.whl (5.7 MB)
Requirement already satisfied: numpy in f:\windrecorder\.venv\lib\site-packages (from torchvision==0.17.0+cu121) (1.26.4)
Requirement already satisfied: requests in f:\windrecorder\.venv\lib\site-packages (from torchvision==0.17.0+cu121) (2.31.0)
Requirement already satisfied: torch==2.2.0+cu121 in f:\windrecorder\.venv\lib\site-packages (from torchvision==0.17.0+cu121) (2.2.0+cu121)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in f:\windrecorder\.venv\lib\site-packages (from torchvision==0.17.0+cu121) (10.2.0)
Requirement already satisfied: filelock in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121->torchvision==0.17.0+cu121) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121->torchvision==0.17.0+cu121) (4.10.0)
Requirement already satisfied: sympy in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121->torchvision==0.17.0+cu121) (1.12)
Requirement already satisfied: networkx in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121->torchvision==0.17.0+cu121) (3.2.1)
Requirement already satisfied: jinja2 in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121->torchvision==0.17.0+cu121) (3.1.3)
Requirement already satisfied: fsspec in f:\windrecorder\.venv\lib\site-packages (from torch==2.2.0+cu121->torchvision==0.17.0+cu121) (2024.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in f:\windrecorder\.venv\lib\site-packages (from requests->torchvision==0.17.0+cu121) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in f:\windrecorder\.venv\lib\site-packages (from requests->torchvision==0.17.0+cu121) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in f:\windrecorder\.venv\lib\site-packages (from requests->torchvision==0.17.0+cu121) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in f:\windrecorder\.venv\lib\site-packages (from requests->torchvision==0.17.0+cu121) (2024.2.2)
Requirement already satisfied: MarkupSafe>=2.0 in f:\windrecorder\.venv\lib\site-packages (from jinja2->torch==2.2.0+cu121->torchvision==0.17.0+cu121) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in f:\windrecorder\.venv\lib\site-packages (from sympy->torch==2.2.0+cu121->torchvision==0.17.0+cu121) (1.3.0)

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

  checking the installation results... 检查安装结果……

   恭喜！你的设备支持 CUDA 加速。
   Congratulations! Your device supports CUDA acceleration.

   uform 已成功安装！
   uform has been successfully installed!
No conda env active, defaulting to base
module 'uform' has no attribute 'models'
   uform 模型似乎下载失败，请检查网络、添加代理或进行重试。
   uform model seems to have failed to download, please check the network, add a proxy, or try again.

  The installation script has been completed. 已执行完安装脚本。

Press any key to continue . . .
```
在interactive shell里运行test.py中内容，如下所示：
```
Windrecorder [ main][!?][📦 v0.0.13][🐍 v3.11.9(windrecorder-py3.11)]
❯ python
Python 3.11.9 (main, Apr 15 2024, 17:44:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import uform
>>> from windrecorder import img_embed_manager
No conda env active, defaulting to base
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Windrecorder\windrecorder\img_embed_manager.py", line 58, in <module>
    def embed_img(model: uform.models.VLM, img_filepath, is_cuda_available=is_cuda_available):
                         ^^^^^^^^^^^^
AttributeError: module 'uform' has no attribute 'models'
>>> img_embed_manager.get_model("cpu")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'img_embed_manager' is not defined
>>>
```

**Comment by Lutra-Fs** [comment]
Once I removed all the typing hint with uform.models.VLM I now get following error:
```
>>> from windrecorder import img_embed_manager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Windrecorder\windrecorder\img_embed_manager.py", line 45, in get_model
    model = uform.get_model("unum-cloud/uform-vl-multilingual-v2")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Windrecorder\.venv\Lib\site-packages\uform\__init__.py", line 187, in get_model
    return get_model_onnx(model_name, device=device, token=token, modalities=modalities)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Windrecorder\.venv\Lib\site-packages\uform\__init__.py", line 155, in get_model_onnx
    encoder = TextEncoder(modality_paths.get(Modality.TEXT_ENCODER), device=device)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Windrecorder\.venv\Lib\site-packages\uform\onnx_encoders.py", line 109, in __init__
  File "F:\Windrecorder\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 372, in __init__
    raise TypeError(f"Unable to load from type '{type(path_or_bytes)}'")
TypeError: Unable to load from type '<class 'NoneType'>'
```

**Comment by Lutra-Fs** [comment]
翻了一下uform库那边， https://github.com/unum-cloud/uform/commit/9bf5fe319d2c32f75bfda1a7a45b86c060b7f0f2#diff-8b72a6352c045b62d5c7c5a1b84f6e6875a35a3bdecd60025fa61815ff13c972
从上个月开始`uform.get_model` 就是默认onnx后端了，因此v2的uform版本的模型可能没有对应的ONNX权重（猜的）。我看作者在引入Chinese OCR的时候引入了onnxruntime，不妨就改成onnx的模型，比装个pytorch还是轻量很多的。就是我不太清楚poetry怎么弄onnxruntime-gpu, 如果作者觉得可以我可以试着改改发PR

**Comment by XiaoNieGPT** [comment]
(windrecorder-py3.11) D:\Windrecorder>python temp.py
No conda env active, defaulting to base
Traceback (most recent call last):
  File "D:\Windrecorder\temp.py", line 2, in <module>
    from windrecorder import img_embed_manager
  File "D:\Windrecorder\windrecorder\img_embed_manager.py", line 58, in <module>
    def embed_img(model: uform.models.VLM, img_filepath, is_cuda_available=is_cuda_available):
                         ^^^^^^^^^^^^
AttributeError: module 'uform' has no attribute 'models'

(windrecorder-py3.11) D:\Windrecorder>

**Comment by Chanli520** [comment]
> (windrecorder-py3.11) D:\Windrecorder>python temp.py No conda env active, defaulting to base Traceback (most recent call last): File "D:\Windrecorder\temp.py", line 2, in from windrecorder import img_embed_manager File "D:\Windrecorder\windrecorder\img_embed_manager.py", line 58, in def embed_img(model: uform.models.VLM, img_filepath, is_cuda_available=is_cuda_available): ^^^^^^^^^^^^ AttributeError: module 'uform' has no attribute 'models'
> 
> (windrecorder-py3.11) D:\Windrecorder>

我全部都解决完了，作者的uform 应该是旧版本的，跟最新版本的不兼容，但是感觉没啥必要弄这个了，因为识别的效果真的很差

**Comment by Chanli520** [comment]
另外OCR的识别 我也转化成了PaddleOCR, OCR的识别效果大大提升，建议作者能优化一下 提交个新版本。

**Comment by Antonoko** [comment]
> 翻了一下uform库那边， [unum-cloud/uform@9bf5fe3#diff-8b72a6352c045b62d5c7c5a1b84f6e6875a35a3bdecd60025fa61815ff13c972](https://github.com/unum-cloud/uform/commit/9bf5fe319d2c32f75bfda1a7a45b86c060b7f0f2#diff-8b72a6352c045b62d5c7c5a1b84f6e6875a35a3bdecd60025fa61815ff13c972) 从上个月开始`uform.get_model` 就是默认onnx后端了，因此v2的uform版本的模型可能没有对应的ONNX权重（猜的）。我看作者在引入Chinese OCR的时候引入了onnxruntime，不妨就改成onnx的模型，比装个pytorch还是轻量很多的。就是我不太清楚poetry怎么弄onnxruntime-gpu, 如果作者觉得可以我可以试着改改发PR

谢谢调查！最开始我在 discord 上询问过开发者是否会合入 onnx 的支持，现在终于加上了🎉，torch runtime 太笨重了、早应该抛弃。我最开始选择 uform 是看到评测数据上以更小体积、更低计算性能持平甚至高于 CLIP 的表现，但现在实际试用下来可能并不是如此，识别效果确实糟糕（可能和只有 256 维的嵌入有关）。如果有更好的嵌入模型也欢迎推荐！或者 uform 模型有提升的情况下，先更换为 onnx 的支持可能更加可行，也比较方便处理历史包袱…

（不过主要的问题还是我作为主要维护者的技术力太糟糕了，很多功能虽然想要优化改进，但受限于能力和时间精力，实现都比较困难甚至是糟糕的，如果有兴趣欢迎提交 PR 一起改进~

**Comment by Antonoko** [comment]
> 另外OCR的识别 我也转化成了PaddleOCR, OCR的识别效果大大提升，建议作者能优化一下 提交个新版本。

（在尝试了在尝试了…希望未来可以加入对更多 OCR 的支持，目前也有个 PR 在准备做这个特性，如果有兴趣也可以加入开发讨论和贡献（现在主要是觉得系统自带的 OCR 对日常检索线索已经够用，而且不需要引入额外的依赖和更多计算资源，不过对于需要精确性的场景确实效果很一般 - -

**Comment by Antonoko** [comment]
我先将 uform 更新到了最新版本的模型和使用 onnx 进行推理，希望识别与召回性能有所改善……欢迎更新体验😇
