### ISSUE TITLE
Latest pull fails until "poetry lock --no-update" is run.

### ISSUE THREAD

**Issue by brimwats** [yuka-friends/Windrecorder#208]
"install_update.bat" Fails on 

```
Creating virtualenv windrecorder in C:\Users\bri\Documents\Windrecorder\.venv
Installing dependencies from lock file

pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.
Traceback (most recent call last):
  File "C:\Users\USER\Documents\Windrecorder\\onboard_setting.py", line 7, in <module>
    from windrecorder import __version__, utils
  File "C:\Users\USER\Documents\Windrecorder\windrecorder\utils.py", line 17, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Press any key to continue . . .
```

solution seems to be `poetry lock --no-update` which grabs a lot more dependencies; not sure if all 22k items are actually required

**Comment by Antonoko** [comment]
thanks for feedback!! it's my silly mistake forgotten to run poetry lock and has been fixed now, please run the install_update.bat to git pull and try again.
