### ISSUE TITLE
install_update报错

### ISSUE THREAD

**Issue by 66bili** [yuka-friends/Windrecorder#246]
ERROR: Could not find a version that satisfies the requirement poetry (from versions: none)
ERROR: No matching distribution found for poetry
Traceback (most recent call last):
  File "C:\Users\anyi\AI\Windrecorder\\onboard_setting.py", line 7, in <module>
    from windrecorder import __version__, utils
  File "C:\Users\anyi\AI\Windrecorder\windrecorder\utils.py", line 18, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by Antonoko** [comment]
你好！看上去是poetry未能正确安装、或相关的依赖和虚拟环境也未能成功安装所导致。请问下python版本是3.10或3.11吗？系统中是否还有安装其他的python环境呢？（可以通过在命令行使用`python --version`查询

**Comment by julystone** [comment]
请问下，是什么原因导致  不支持python12版本 @Antonoko
